### ISSUE TITLE
Unknown package perl2.rs-modules

### ISSUE THREAD

**Issue by Alexkurd** [gl-inet/glbuilder#2]
Is it correct package naming?

`sudo apt update`
`sudo apt install device-tree-compiler g++ ncurses-dev python asciidoc bash bc binutils bzip2 fastjar flex gawk gcc genisoimage gettext git intltool jikespg libgtk2.0-dev libncurses5-dev libssl-dev make mercurial patch >>perl2.rs-modules<< python ruby sdcc subversion unzip util-linux wget xsltproc zlib1g-dev zlib1g-dev -y`

E: Unable to locate package perl2.rs-modules
E: Couldn't find any package by glob 'perl2.rs-modules'
E: Couldn't find any package by regex 'perl2.rs-modules'

Maybe it should be `perl-modules`?

**Comment by luochongjun** [comment]
Thanks, Fixed in this commit https://github.com/gl-inet/glbuilder/commit/055249a9949d26fd4dfec0f05aaf94fdd8a85010
